#!name=AppRaven
#!desc=Premium
#!author=Yu9191
#!icon=https://raw.githubusercontent.com/Game-2020/icon/main/AppRaven.png
#!category=G
#!openUrl=https://apps.apple.com/
#!tag=会员
#!system=ios
#!loon_version=3.2.1(732)
#!homepage=https://github.com/Yu9191
#!date=2024-08-15 00:00:00

[Script]
AppRaven = type=http-response, pattern=https://appraven.net/appraven/graphql, script-path=https://raw.githubusercontent.com/Game-2020/Loon/main/Script/AppRaven.js, requires-body=true, timeout=60

[MITM]
hostname = %APPEND% appraven.net
